communitiesuk/funding-service-design-utils

- fsd_utils/healthchecks/checkers.py
- setup.py
Removed type hint for FlaskRedis as it meant anything using this version of utils needed the redis_flask library on its path.
> Fix redis import

- fsd_utils/gunicorn/config/devtest.py
- setup.py
PaaS hits the healthcheck very frequently which clutters our logs.
This filters out the access logs for that route. We will still get any error/exception logs should it fail.
> BAU: Filter healthcheck from access logs

- .github/workflows/test-and-tag.yml
- README.md
- pyproject.toml
- setup.py
Changes to the workflow to push the package up to PyPI.org when we create a tag on main.
Published to pypi-test while working on this: https://test.pypi.org/project/funding-service-design-utils/
> FS-1135 - Publish to PyPI

- README.md
- fsd_utils/__init__.py
- fsd_utils/sentry/init_sentry.py
- pyproject.toml
Adds Sentry integration, have tested locally by setting `SENTRY_DSN` on local frontend app, code is as per: https://docs.sentry.io/platforms/python/guides/flask/
> FS-1401: sentry integration

- fsd_utils/config/commonconfig.py
- pyproject.toml
Adding the WTF_CSRF_TIME_LIMIT and FSD_SESSION_TIMEOUT_SECONDS env-vars to be called in the frontend and authenticator services for timeout scenarios.
> Fs 1625 add csrf token time limit env var

- README.md
- fsd_utils/sentry/init_sentry.py
- pyproject.toml
This is useful to corrolate errors with releases
- add version to sentry init if specified
- bump version number
> FS-1401: add version to sentry init (if specified)

- fsd_utils/locale_selector/get_lang.py
- pyproject.toml
- tests/test_get_lang.py
We don't want the Welsh translations to be accessible until they are complete, so commenting out the functionality for now which sniffs locale based on the browser's settings.
> FS-1736: disable language sniffing

- fsd_utils/sentry/init_sentry.py
- pyproject.toml
PaaS polling the `/healthcheck` endpoint used up all of our transaction allowance, we can filter out that endpoint from being included in future. This is as per Sentry documentation https://docs.sentry.io/platforms/python/configuration/filtering/#using-sampling-to-filter-transaction-events and has been tested locally.
> FS-1855: filter healthcheck endpoint from sentry transaction monitoring

- fsd_utils/config/commonconfig.py
**Jira Ticket:**
https://digital.dclg.gov.uk/jira/browse/FS-1870
The following form names had the incorrect Welsh translation:
- Community engagement 
- Funding required
- Upload business plan
- Project qualification 
Which returned a 500 when trying to click on one of these forms locally. 
I have now fixed the Welsh spelling for these form names. I got the spelling from the welsh form json files in the frontend repo:
https://github.com/communitiesuk/funding-service-design-frontend/tree/main/form_jsons/public/cy
> FS-1870 - Correct Welsh form names to the correct spelling

- fsd_utils/locale_selector/get_lang.py
- pyproject.toml
- tests/test_get_lang.py
Re-enabled locale sniffing.  Will infer language from headers if cookie isn't set.
Tested locally:  (and there are code tests that existed)
https://user-images.githubusercontent.com/117724519/206164120-54642934-40ef-43d8-b591-ed3ff38938df.mp4
> FS-1773: Enable locale sniffing from headers

- fsd_utils/authentication/decorators.py
- pyproject.toml
- tests/conftest.py
- tests/test_authentication.py
- When FLASK_ENV == "development" and DEBUG_USER and DEBUG_USER_ROLE config vars are set, then use these values to set the request user and roles (instead of the fsd_user_token cookie) - this is to allow easy checking of functionality during local development on routes decorated with the @login_required decorator
> BAU: add debug user role bypass to auth

- fsd_utils/logging/logging.py
- pyproject.toml
Remove extraneous logging of healthcheck, and erroneous error logging in `after_request` method.
This should remove the erroneous errors as seen below, as this will only log at `info` level now.
> BAU: don't log healthcheck and only log after_request at info level

- fsd_utils/__init__.py
- fsd_utils/authentication/models.py
- fsd_utils/sentry/init_sentry.py
- pyproject.toml
see https://docs.sentry.io/platforms/python/guides/flask/enriching-events/identify-user/ for context
I have tested this using a branch of utils on assessment and I can see the user context coming through e.g.
> FS-2159: set user in sentry

- README.md
- fsd_utils/__init__.py
- fsd_utils/config/commonconfig.py
- fsd_utils/simple_utils/data_utils.py
- fsd_utils/simple_utils/date_utils.py
- pyproject.toml
- requirements-dev.txt
- tests/test_cof_dates.py
- tests/test_data_utils.py
Adding logic to determine default round ID based on env vars. Allos the cof r2w3 launch date to be overridden by an env var and then determines the default round ID based on whether or not that round is open yet.
> Fs 2181 default ids

- fsd_utils/sentry/init_sentry.py
- pyproject.toml
Exclude performance tests from sentry request sampling as processing large amounts of requests causes us to exceed quotas.
Was tested manually by dumping out sentry sampling context to work out correct value from event to filter.
> FS-1200: exclude performance tests from sentry request sampling

- README.md
- fsd_utils/__init__.py
- fsd_utils/config/commonconfig.py
- fsd_utils/toggles/__init__.py
- fsd_utils/toggles/toggles.py
- pyproject.toml
- requirements-dev.txt
FS-2277: Spike: Feature Toggles
Added the toggles module to utils that contains the functions to initialize the redis store, create a redis client and load it with the toggles using a pre-defined feature_configuration.
checkout to this branch along with [this ](https://github.com/communitiesuk/funding-service-design-docker-runner/pull/28)in docker runner and [this ](https://github.com/communitiesuk/funding-service-design-assessment/pull/191)in assessment and see flagging functionality hidden from the user. (More info on running this E2E can be found in the description of the above assessment PR^.
See [this doc](https://digital.dclg.gov.uk/confluence/display/FS/Feature+Toggles+in+FSD) for more information on methodology, set up and how to use.
> fs-2277-toggles

- pyproject.toml
Bumping version to 1.0.25 after merging fs-2277-toggles, did not originally bump the version high enough.
> BAU bump version for fs-2277-toggles

- fsd_utils/toggles/toggles.py
- pyproject.toml
Adding config prefix to FlaskRedis object to allow toggle client to use the appropriate redi uri
> fs-2514-multifund-redis-setup

- fsd_utils/authentication/config.py
- fsd_utils/authentication/decorators.py
- pyproject.toml
- tests/conftest.py
- tests/test_authentication.py
https://trello.com/c/tQ3rDYzh/328-implement-authentication-changes-into-front-end-auth-utils-and-docker-runner
Adds a new parameter `return_app` to the `login_required` decorator that enables authenticator to redirect back to FSD applications other than Assessment
- [NA] README and other documentation has been updated / added (if needed)
> PAB-328: add return_app param to login_required decorator

- fsd_utils/authentication/config.py
- fsd_utils/authentication/models.py
- fsd_utils/authentication/utils.py
- tests/conftest.py
- tests/test_authentication.py
- tests/test_utils.py
The `azure_ad_role_map` has been updated based on the theoretical mappings from Azure AD - these may be wrong and need changed depending on what has been configured for us, the old roles are now mapped to COF.
Instead of having a `highest_role`, we now have a `highest_role_map` which maps `fund_short_name -> highest_role`, this is because different users may have different highest roles between funds, so we need a way to track them.
https://github.com/communitiesuk/funding-service-design-account-store/pull/96
https://github.com/communitiesuk/funding-service-design-assessment-store/pull/198
https://github.com/communitiesuk/funding-service-design-assessment/pull/275
https://github.com/communitiesuk/funding-service-design-authenticator/pull/169
> FS-2990 & 2989: Devolved authorities & fund specific access

- fsd_utils/authentication/config.py
- pyproject.toml
we no longer need a check against valid roles as the deprecated roles are no longer being used.
> remove deprecated config

- README.md
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
> Updated utils readme

- fsd_utils/eoi/evaluate_eoi_response.py
- pyproject.toml
- tests/test_eoi.py
Fix that casts any values passed to the operator evaluation function to a number as they are sent as strings in the form json responses
> fs-4035 handling numbers passed in as strings

- fsd_utils/mapping/application/application_utils.py
- pyproject.toml
- tests/test_mapping_application.py
- Add language to methods used for formatting answers
- Update unit tests to include all cases of EN/CY
- Note, the reason for hardcoded translations are that these are used in places without pybabel (i.e application store)
---
> FS-4253: Add translation to answer formatters

- fsd_utils/__init__.py
- fsd_utils/decision/evaluate_response_against_schema.py
- pyproject.toml
- tests/test_decisions.py
I think we will need to use the mechanisms for EOI to evaluate eligibility responses as well, so just updating the name to remove EOI and make it a generic `decision` feature
> fs-3530 removing eoi from decision naming

- fsd_utils/locale_selector/get_lang.py
- pyproject.toml
- tests/test_get_lang.py
We get a lot of sentry errors about invalid language code - changing this to a warning instead of an exception, and defaulting to english which will stop the sentry errors
> fs-3993 removing alert for invalid language

- fsd_utils/services/aws_extended_client.py
- fsd_utils/services/aws_sqs_extended_client_util.py
- pyproject.toml
- tests/test_sqsextendedclient.py
https://dluhcdigital.atlassian.net/browse/FS-3535
adding the capability to SQS extended client's S3 to have custom S3Key
> FS-3535 : adding a custom s3 key for the message that sent through extended client

- fsd_utils/logging/logging.py
- pyproject.toml
- tests/test_logging.py
https://dluhcdigital.atlassian.net/browse/FPASF-104
This allows each app to adjust the log configuration if needed. It moves us from an imperative log configuration flow to a declarative one - we just say what we want in a readable dict, and then logging sets it up as specified. It should be easier to debug logging issues and understand exactly what loggers we're setting up.
This will initially be used by the data-store to grab the default logging config and inject it into our new celery worker, as celery's logger needs to be set up separately (ie not via the flask app).
> Convert logging.init_app to use dictConfig

- fsd_utils/authentication/decorators.py
- pyproject.toml
- tests/test_authentication.py
adds `request_path` to sign-out url.
This is used by authenticator to redirect to a custom path within the targeted `return_app`
If using this version of utils, `request_path` query param should be appended to signed out route if `return_app` is in query params.
> FPASF-376: add request path to sign-out url

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- pyproject.toml
This means that `flipper-client` will only be installed if the `toggles` extra is requested by the service pulling in fsd-utils.
> Make `toggles` an optional extra

- CHANGELOG.md
- fsd_utils/authentication/decorators.py
- pyproject.toml
Always try to check the access token in the cookie before checking the debug user.
This means that you can still authenticate normally via a cookie, but if that fails, you fall back to the debug user.
> Check auth token before falling back to debug user

- pyproject.toml
- pytest.ini
We have two warnings on the repo at the moment, both from dependencies (so outside of our control). One is from botocore
(https://github.com/boto/boto3/issues/3889) and the other is from sqlalchemy. Both are Python 3.12 DeprecationWarnings about datetime.datetime.utcnow and datetime.datetime.utcfromtimestamp being scheduled for removal in future python versions.
```
================================================== 204 passed, 10 warnings in 1.76s ===================================================
```
```
========================================================= 204 passed in 1.71s =========================================================
```
> Turn warnings into errors; acknowledge existing errors

- pyproject.toml
fsd-utils is a library that should be usable with a broad set of dependencies. By pinning upper bounds, despite having no concrete evidence that fsd-utils is incompatible with new releases, we make it harder for any apps using fsd-utils to pull in other dependencies.
> Stop pinning upper bounds of fsd-utils

- pyproject.toml
Adding boto3 into the dependencies in [pyproject.toml](./pyproject.toml). Since making toggles an optional extra, `boto3` is not longer installed as a transient dependency of `flipper-client`. But it is needed to load the `configclass` which is used without `flipper-client`
> BAU including boto3 so config class continues to work for consumers

- CHANGELOG.md
- pyproject.toml
FSD-utils is a library package meant to be installed in a variety of
other applications.
Those applications may themselves require other/specific versions of
dependencies. This library should be compatible with as many variations
of dependencies as possible so that it can be installed in all of our
apps with minimal risk of compatibility issues.
So we should not be pinning specific versions here, and instead just say
what range of dep versions should be compatible.
> Un-pin dependencies

- CHANGELOG.md
- fsd_utils/config/configclass.py
- pyproject.toml
Allow for the Table config print to be optional.
Default behaviour prints the table, as before.
Set `FSD_UTILS_ENABLE_CONFIG_TABLE` to "false". To turn it off.
Not very easy..
- Set `FSD_UTILS_ENABLE_CONFIG_TABLE=false` in the docker runner
- Install this branch version of utils by updating the requirements.txt with
```
funding-service-design-utils @ git+https://github.com/communitiesuk/funding-service-design-utils@327697124975ac550874448512c1b4a88501b31f
```
- The service that uses this version of utils will not print a table
Or... 
Take my word for it. :+1:
> Make config table optional

- CHANGELOG.md
- fsd_utils/locale_selector/set_lang.py
- pyproject.toml
- tests/test_set_lang.py
This reverts commit 8e7e0500b320c76e58ea1f4a6a583d73b15e05aa.
The apps themselves control these attributes through SESSION_COOKIE_* config options, so it's a bit inconsistent to override this.
It also means that the cookie may not be passed through for insecure HTTP on local development, which is still used by pre-award.
> Revert "Set cookie attributes for "security""

- CHANGELOG.md
- pyproject.toml
- requirements-dev.txt
Bumps our local pre-commit version to be >=4.0. This matches what runs in pre-commit.ci, so is best to keep roughly in sync.
In particular this bump has been prompted by CI failures on the assessment-store, where one of the installed hooks is incompatible with v4 of pre-commit because the `python_venv` "language" has been removed. We don't see this issue locally on that repo because we're still running an older version of pre-commmit.
> Upgrade pre-commit

- pyproject.toml
- renovate.json
For libraries, we generally want to support ranges of versions rather than just specific versions of things (the latter makes more sense for applications). Our [central config](https://github.com/communitiesuk/renovate-config) is specced for applications
This change will make renovate support ranges in pyproject.toml, and replace the range only when a new version of a dependency falls outside of that range.
Eg if we pinned `Flask~=2.0`, then when Flask 3.0.0 is released it would bump it to `Flask~=3.0`.
> Override the central rangeStrategy=pin

- fsd_utils/config/commonconfig.py
- pyproject.toml
- tests/test_config.py
- uv.lock
Updating the check in `CommonConfig` for the `SECRET_KEY` to use a `not in` check for whether to raise an error. This should fix an issue where the post award services were throwing an error on production because there is a difference in environment naming between pre and post award (`prod` vs `production`)
> Changing to a negative check for the environment list

- .github/workflows/increment-version.yml
- pyproject.toml
- uv.lock
Now we use `uv` to manage dependencies, the version in `pyproject.toml` is used to reference the utils package. This PR adds a `uv lock` call to the version increment job to that `uv.lock` is kept in sync with `pyproject.toml`
> Running uv lock when version incremented

- CHANGELOG.md
- fsd_utils/authentication/config.py
- fsd_utils/authentication/decorators.py
- pyproject.toml
- tests/conftest.py
- tests/test_authentication.py
- uv.lock
- [Add authentication to FAB](https://mhclgdigital.atlassian.net/browse/FS-4805)
- [Share check internal user functionality across apps](https://mhclgdigital.atlassian.net/browse/FS-4871)
- [Form Designer authentication](https://mhclgdigital.atlassian.net/browse/FS-4794)
**Add authentication to FAB**
FAB needs to be added to the `SupportedApp` enum in order to be authenticated.
**Share check internal user functionality across apps** (sub-task of "Add authentication to FAB")
This functionality already exists in Post-Award Data Store, here: https://github.com/communitiesuk/funding-service-design-post-award-data-store/blob/main/find/main/decorators.py
Now this functionality is required by FAB, so we need to move that functionality to a shared location i.e., utils library.
Once this PR is …
> FS-4805 - FAB authentication

- CHANGELOG.md
- fsd_utils/logging/logging.py
- pyproject.toml
- uv.lock
```
fsd_utils/logging/__init__.py:2: in <module>
from . import logging
fsd_utils/logging/logging.py:13: in <module>
from pythonjsonlogger.jsonlogger import JsonFormatter as BaseJSONFormatter
.tox/py3.10-flask2.2-sqlalchemy2/lib/python3.10/site-packages/pythonjsonlogger/jsonlogger.py:11: in <module>
warnings.warn(
E   DeprecationWarning: pythonjsonlogger.jsonlogger has been moved to pythonjsonlogger.json
```
> Resolve DeprecationWarning

- CHANGELOG.md
- fsd_utils/authentication/config.py
- pyproject.toml
- uv.lock
We want to add the ability to login via SSO to the platform, but we don't currently have proper domains which will make integrating with Microsoft AD infeasible.
As a temporary step, we're going to proxy auth via the existing authenticator service. Once we've got our domains set up, we'll tear down this logic and build an SSO flow as part of the funding-service repo directly.
In order to support proxying auth via authenticator, we'll set up the new funding-service as a safe return app.
We expect this proxying behaviour to last 1-2 weeks.
https://mhclgdigital.atlassian.net/browse/FSPT-393
> Add platform as supported app temporarily

- fsd_utils/mapping/application/multi_input_utils.py
- tests/test_data_utils.py
Fixes an issue where submitting a form with MultiInput Field having identical values across all input fields [caused an error](https://funding-service-design-team-dl.sentry.io/issues/6677776751/?alert_rule_id=15583723&alert_type=issue&notification_uuid=cb97fa94-1329-4852-9984-e5f081e63e7d&project=4508324370317312&referrer=slack) during Q&A generation. The root cause was that all values were being skipped due to the removal of all instances of a repeated value.
- Updated logic to convert dictionary values to a list and remove **only the first occurrence** of the specified key value.
- Ensures that repeated values are preserved, preventing unintended data loss.
> Fix MultiInput Mapping Error for repeating inputs
