communitiesuk/funding-service-design-utils

fsd_utils/__init__.py, setup.py
Updated setup.py to include new sub folder.
=> Bug lost init

fsd_utils/__init__.py, fsd_utils/config/commonconfig.py, fsd_utils/config/configclass.py, setup.py
Added common config class and moved in values for assessment and assessment-store
=> Fs 1169 common config

setup.py
Forgot to do this in the common config branch D'Oh
=> changed version

fsd_utils/healthchecks/checkers.py, requirements-dev.txt, setup.py, tests/test_checkers.py, tests/test_healthcheck.py
Added a new checker to the healthcheck util to check redis is running
=> Bau redis healthcheck

fsd_utils/authentication/decorators.py
=> FS-1322 - Update failed auth redirect endpoint

setup.py
=> FS-1322 Update version to 0.0.16

README.md, fsd_utils/__init__.py, fsd_utils/config/commonconfig.py, fsd_utils/locale_selector/__init__.py, fsd_utils/locale_selector/get_lang.py, fsd_utils/locale_selector/set_lang.py, requirements-dev.txt, setup.py, tests/conftest.py, tests/test_get_lang.py, tests/test_set_lang.py
Adds locale selection functionality for translations, usage in apps is as per README.
(Adapted from the spike done on Frontend https://github.com/communitiesuk/funding-service-design-frontend/compare/welsh)
=> FS-1274: adds locale selection functionality

README.md, fsd_utils/locale_selector/set_lang.py, setup.py, tests/conftest.py
Small follow-up after #20 to address comment from @harryyo
=> FS-1274: change cookie name

fsd_utils/__init__.py, fsd_utils/config/commonconfig.py, fsd_utils/config/notify_constants.py, setup.py
Moved notify constants out into a separate class
=> Bau notify fields

fsd_utils/authentication/config.py, fsd_utils/authentication/decorators.py, setup.py
=> FS-1450 Add auth creds to request context

fsd_utils/sentry/init_sentry.py, pyproject.toml
Fix after #35 
Fix incorrect version key see: https://docs.sentry.io/platforms/python/configuration/releases/#bind-the-version
=> FS-1401: fix sentry release key

pyproject.toml
Forgot to bump version in last PR so release failed 🤦
=> FS-1401: bump version

fsd_utils/config/commonconfig.py, pyproject.toml
adding english and welsh keys and values to form conifg
=> Fs 1859 centralize form config

fsd_utils/config/commonconfig.py
Reverts communitiesuk/funding-service-design-utils#44
=> Revert "FS-1870 - Correct Welsh form names to the correct spelling"

fsd_utils/config/commonconfig.py, pyproject.toml
Created a new PR relating to this revert:
https://github.com/communitiesuk/funding-service-design-utils/pull/45
As I forgot to update version number.
=> Corrected Welsh form names and incremented version

fsd_utils/config/commonconfig.py, pyproject.toml
Fix console errors to do with inline styling
=> Fixing styleing console issues

fsd_utils/healthchecks/healthcheck.py, pyproject.toml, tests/test_healthcheck.py
Pass through version to healthcheck endpoint
=> FS-2172: include version in healthcheck (if supplied)

fsd_utils/config/commonconfig.py, pyproject.toml
Updating toggle list to include a toggle for multi-fund-dashboard
=> Fs 2514 multifund dashboard

.pre-commit-config.yaml, fsd_test_utils/fixtures/db_fixtures.py, fsd_utils/authentication/decorators.py, fsd_utils/config/commonconfig.py, fsd_utils/gunicorn/config/devtest.py, fsd_utils/gunicorn/config/local.py, fsd_utils/healthchecks/healthcheck.py, fsd_utils/locale_selector/set_lang.py, fsd_utils/logging/logging.py, tests/conftest.py, tests/test_authentication.py, tests/test_data_utils.py, tests/test_get_lang.py, tests/test_set_lang.py
- Add flake8 argument for 120 line length
- Remove black argument for line length
=> FS-2689: Change maximum line length to 120

tests/test_checkers.py
Investigate failing healthcheck tests on Utils
https://digital.dclg.gov.uk/jira/browse/FS-2781
Solution
Check mock call args directly.
All tests passing.
=> Refactor health checkers test

fsd_utils/simple_utils/date_utils.py, pyproject.toml
Adding datetime conversions to dateutils so time checking for opening rounds uses localised time.
=> fs-2892-date-logic

fsd_utils/authentication/decorators.py, fsd_utils/authentication/utils.py, pyproject.toml, tests/conftest.py
Updating the `DEBUG_USER` capability to include an account_id so that we can mock more calls within assessment.
=> Fs 2291 debug user

pyproject.toml
Bumping version cause I forgot
=> BAU: Bump version to 2.0.8

fsd_utils/mapping/application/application_utils.py, fsd_utils/mapping/application/multi_input.py, fsd_utils/mapping/application/qa_mapping.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?view=detail&selectedIssue=FS-3036
This PR addresses several improvements:
- Bug fixes for the funding required form mapping and formatting in a text file. 
- It enhances the formatting of date-time year values.
- Removes null values from strings, list. 
- Updates the radio button's answer and strings by removing the "-" character, excluding those that are part of an HTTP or HTTPS link.
=> FS-3036-bug-fix-map-application-q-a-for-text-file

fsd_utils/mapping/application/application_utils.py, fsd_utils/mapping/application/multi_input.py, fsd_utils/mapping/application/qa_mapping.py, fsd_utils/simple_utils/data_utils.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
https://dluhcdigital.atlassian.net/browse/FS-2878
This PR address the following issues and improvements:
- Eliminate hyphens from the radio field
- Improve the readability of the monthYear field type formatting
- Enhance the overall text file formatting to improve readability
Added unit tests
=> FS-2878-format-enhancement-of-a-text-file-for-better-redability

pyproject.toml
=> FS-3101: Bump utils version

fsd_utils/authentication/config.py, pyproject.toml
Add submit as a supported app.
=> add submit as supported app

fsd_test_utils/test_config/useful_config.py
Adding IDs for COF R3W1 and NSTF into testing config
=> adding fund/round ids to useful config

.github/workflows/increment-version.yml, .github/workflows/test-and-tag.yml, README.md, pyproject.toml
Moving the auto bump to a separate workflow triggerred on a PR as we can't push directly to main
=> unable to push to master - added bump to PR action

.github/workflows/test-and-tag.yml
=> bau correct tag var name

fsd_test_utils/test_config/useful_config.py, pyproject.toml
=> Added cof r3w2 id

fsd_utils/sentry/init_sentry.py, pyproject.toml
* Enable [Sentry Profiler](https://docs.sentry.io/platforms/python/profiling/)
* Makes sample rate overridable via env var
Have tested locally and can see profile transaction in sentry
=> FMD-50: Enable sentry profiler

fsd_utils/mapping/application/multi_input.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
This PR fixes the mapping and form atting issue for new fund CYP
https://dluhcdigital.atlassian.net/browse/FS-3510
=> FS-3510-fix-data-mapping-and-formatting-for-cyp

fsd_utils/mapping/application/multi_input.py, pyproject.toml
This PR is  just to bump the sentry-sdk version to 1.18.0
=> sentry-sdk-bumped-to-1.18.0

fsd_utils/mapping/application/multi_input.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
This PR fixed key:value pair formatting issue for month year component in the multiInput field 
https://dluhcdigital.atlassian.net/browse/FS-3529
=> FS-3529-fix-add-another-multi-input-date-formatting

fsd_utils/mapping/application/application_utils.py, fsd_utils/mapping/application/multi_input.py, fsd_utils/mapping/application/multi_input_utils.py, fsd_utils/mapping/application/qa_mapping.py, pyproject.toml, tests/conftest.py, tests/test_authentication.py, tests/test_data_utils.py, tests/test_mapping_application.py
https://dluhcdigital.atlassian.net/browse/FS-3524
>  removed "cyp" title at end of the form title
> unnecessary error logs replaced with infor or warning
> exclude display of the 'Do you want to mark this section as complete?' question in the text file
> refactored mapping and formatting for multiInput field 
> refactored authentication tests. Docs to set_cookie https://werkzeug.palletsprojects.com/en/2.3.x/test/#:~:text=set_cookie(key,origin_only%20parameters%20instead
unit tests
=> FS-3524-cosmetic-fixes-for-cyp-text-file-post-application-submission

fsd_utils/mapping/application/multi_input.py, fsd_utils/mapping/application/multi_input_utils.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
https://dluhcdigital.atlassian.net/browse/FS-3524
- fixed return of the empty string related to address values 
- adjusted indentation for better readability
- added more test data to verify the fix
unit test
=> bug-fix/FS-3524-cosmetic-fixes-for-text-file

fsd_utils/mapping/application/multi_input_utils.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&quickFilter=344&selectedIssue=FS-3524
The int value was not rendering due to missing int type validation
=> bug-fix-int-value/FS-3524-cosmetic-fixes-for-text-file

fsd_utils/sentry/init_sentry.py, pyproject.toml
Reducing default Sentry sample rate as we are over-using our quota. We can still override this via env var per app if we have a specific use case.
Sentry quota usage should go down after deployment
=> BAU: reduce sample rate

fsd_utils/mapping/application/application_utils.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&quickFilter=344&selectedIssue=FS-3591
Formats application answers for dpi fund for better readability.
unit tests
=> FS-3591-improve-readability-for-dpi-fund

fsd_utils/__init__.py, fsd_utils/services/__init__.py, pyproject.toml
https://dluhcdigital.atlassian.net/browse/FS-3431
Added init files
=> Add init file sqs

fsd_utils/mapping/application/multi_input_utils.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
bug-fix/application-mapping-none-values-not-mapping
unit test added
=> bug-fix-application-mapping-none-values-not-correctly-mapping

fsd_utils/config/commonconfig.py, pyproject.toml
https://dluhcdigital.atlassian.net/browse/FS-3606
Added the sha's of the GA4 scripts to the CSP, also included the google tag manager and analytics domains that run scripts too
=> Google analytics setup CSP update

fsd_utils/services/aws.py, pyproject.toml, tests/test_sqsclient.py
https://dluhcdigital.atlassian.net/browse/FS-3703
Synchronized queue attributes settings in localstack similar to the AWS import queue attributes
=> FS-3703 update submit msg function

.github/workflows/increment-version.yml, .github/workflows/test-and-tag.yml, pyproject.toml
Bumping action versions to remove warnings, in line with actions we use in other repos
=> BAU bumping action versions to remove warnings

.github/workflows/increment-version.yml, pyproject.toml
Since updating actions, git couldn't commit the version increment. Now including an email address
=> bau adding email to git settings for committing version bump

fsd_utils/gunicorn/config/devtest.py, fsd_utils/logging/logging.py, pyproject.toml
This filter was specific to Cloudfoundry so can be safely removed
Should have no effect on current logging, as should not be able to hit this code path on AWS.
=> BAU: remove unused filter

.vscode/launch.json, fsd_utils/mapping/application/qa_mapping.py, pyproject.toml, tests/test_data_utils.py, tests/test_mapping_application.py
https://dluhcdigital.atlassian.net/browse/FS-2940
Adding welsh option for yes No
=> FS-2940 - Fix yes no appearing only in English

fsd_utils/mapping/application/application_utils.py, fsd_utils/mapping/application/languages.py, fsd_utils/mapping/application/multi_input.py, fsd_utils/mapping/application/qa_mapping.py, tests/test_mapping_application.py
- Update Welsh translations and functions utilising them
- Change "Ydw" to "Oes" since that's what the form builder shows
---
=> FS-4253: Update Welsh translations

fsd_test_utils/test_config/useful_config.py, tests/test_authentication.py
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
=> FS-4389: HSRA ids added

fsd_utils/services/aws_extended_client.py, fsd_utils/services/aws_sqs_extended_client_exception.py, fsd_utils/services/aws_sqs_extended_client_util.py, pyproject.toml, tests/test_sqsextendedclient.py
[
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_](https://dluhcdigital.atlassian.net/browse/FS-3535)
sqs extended client to handle larger messages while sending through SQS service
=> FS-3535 : sqs extended client to handle larger messages while sending through SQS service

pyproject.toml
[_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
](https://dluhcdigital.atlassian.net/browse/FS-3535)
Updating the version
=> FS-3535 : bumping up the version number

.github/workflows/test-and-tag.yml, README.md, pyproject.toml, requirements-test.txt
FSD-utils can be installed with different python and flask versions. We should comprehensively test these combinations to ensure obscure bugs/incompatibility issues don't sneak in.
=> Add matrix testing via tox

pyproject.toml
Bump sentry_sdk to v2+
This is sentry's changelog for any breaking changes from v2.0.0:
https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#removed
I don't see anything listed there that would affect us - but be aware
when updating your apps to check for how you're using sentry.
=> Bump sentry_sdk to v2+

pyproject.toml
Updating the version of python-dotenv as it conflicts with the upgrades from the dependency work
=> updating dotenv version

pyproject.toml
Force bump of version as version already existed so tagging failed in https://github.com/communitiesuk/funding-service-design-utils/actions/runs/9936705330/job/27445583381
=> BAU: bump version

CHANGELOG.md, fsd_utils/locale_selector/get_lang.py, pyproject.toml, tests/test_get_lang.py
set default language to "en" if language passed in cookie is non supported in FSD.
- [ x] README.md, CHANGELOG.md and other documentation has been updated / added (if needed)
Manually tested replicating error setting cookie no non-supporting language
=> bugfix/get language cookie- fix sentry errors "UnknownLocaleError locale"

CHANGELOG.md, pyproject.toml
Updating utils version
_A brief description of the pull request_
- [ x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
=> Update utils version

fsd_utils/locale_selector/set_lang.py, pyproject.toml, tests/test_set_lang.py
For the language cookie this is not overly important, but github copilot has flagged an issue so just to resolve that, I guess...
Fixes: https://github.com/communitiesuk/funding-service-design-utils/issues/174
=> Set cookie attributes for "security"

.github/workflows/test-and-tag.yml, CHANGELOG.md, pyproject.toml
=> Fix packaging and publishing

fsd_test_utils/test_config/useful_config.py, pyproject.toml, uv.lock
https://mhclgdigital.atlassian.net/browse/FLS-827
- Added hsra round ids
=> HSRA round ids

CHANGELOG.md, fsd_test_utils/fixtures/db_fixtures.py, pyproject.toml
Accompanies https://github.com/communitiesuk/funding-service-pre-award/pull/160
As the above changes the path to the `config` module, the utils files that rely on this location need updating too.
=> Fspt 206 path change

fsd_utils/config/commonconfig.py, pyproject.toml, uv.lock
MULTIFUND_DASHBOARD feature toggle configs removed as they … are not being used anywhere
_A brief description of the pull request_
=> FLS-1077: MULTIFUND_DASHBOARD feature toggle configs removed

CHANGELOG.md, pyproject.toml, uv.lock
- Bump version to 6.1.4 and update CHANGELOG for MultiInput field error fix from [previous PR](https://github.com/communitiesuk/funding-service-design-utils/pull/239)
=> Bump version to 6.1.4 and update CHANGELOG for MultiInput field error fix
